HackedNews/Controllers/AdminController.cs
using System.IO;
using System.Linq;
using HackedNews.Data.Interfaces;
using HackedNews.Data.Models.NewsModel;
using HackedNews.ViewModels;
using Korzh.EasyQuery.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;

namespace HackedNews.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IStringLocalizer<AdminController> _localizer;
        private readonly IAllNews _allNews;
        private readonly SelectList _category;

        public AdminController(IAllNews news, INewsCategory newsCategory, IStringLocalizer<AdminController> localizer)
        {
            _allNews = news;
            _localizer = localizer;
            _category = new SelectList(newsCategory.AllCategories, "Id", "Name");
        }


        public ActionResult Index()
        {
            return View(
                new NewsViewModels
                {
                    News = _allNews.News.AsQueryable()
                }
            );
        }

        [HttpPost]
        public ActionResult Index(NewsViewModels model)
        {
            if (!string.IsNullOrEmpty(model.Text))
                model.News = _allNews.News.AsQueryable().FullTextSearchQuery(model.Text);
            else
                model.News = _allNews.News.AsQueryable();
            return View(model);
        }

        public ActionResult Edit(int newsId)
        {
            ViewBag.Categories = _category;
            return View(_allNews.News.FirstOrDefault(p => p.Id == newsId));
        }


        [HttpPost]
        public ActionResult SwitchImgLoad(News news)
        {
            ViewBag.Categories = _category;
            return View("Edit", news);
        }


        //Создаем новую подтему в форме Edit
        [HttpPost]
        public ActionResult AddSubTopics(News news)
        {
            if (ModelState.IsValid)
                news.ListNewsDatas.Add(new NewsData
                    { Subtitle = "", ImgLink = "", Txt = "", ImgLoad = null, SwitchLoadImg = false });
            ViewBag.Categories = _category;
            return View("Edit", news);
        }

        //Удаляем подтему в форме Edit
        [HttpPost]
        public ActionResult DelSubtopics(News news)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Categories = _category;
                news.ListNewsDatas.Remove(news.ListNewsDatas.Last());
            }

            ViewBag.Categories = _category;
            return View("Edit", news);
        }


        private byte[] GetMassBinary(IFormFile img)
        {
            byte[] imageData = null;
            try
            {
                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(img.OpenReadStream()))
                {
                    imageData = binaryReader.ReadBytes((int)img.Length);
                }
            }
            catch
            {
                imageData = null;
                TempData["err_message"] = _localizer["ErrReaderImg"] + img.FileName;
            }

            return imageData;
        }

        [HttpPost]
        public IActionResult Edit(News news)
        {
            // todo отрефакторить булщитный код написанный много лет назад на скорости из-за дедлайна(goto осуждаю)
            var err = false;
            var not_get_img_err = false; // проверка только для превью на главной страницы
            link:
            //Смог ли процесс привязки модели проверить достоверность отправленных пользователем данных
            if (ModelState.IsValid && !not_get_img_err && !err)
            {
                if (news.File != null)
                {
                    news.ImgLoad = GetMassBinary(news.File);
                    if (news.ImgLoad != null)
                    {
                        news.ImgLink = null;
                        news.File = null;
                    }
                    else
                    {
                        err = true;
                        goto link;
                    }
                }
                else if (news.File == null && news.ImgLink == null)
                {
                    not_get_img_err = true;
                    TempData["err_message"] = _localizer["NotGetPreview"];
                    goto link;
                }

                if (news.ListNewsDatas.Where(p => p.File != null).Count() > 0)
                    foreach (var item in news.ListNewsDatas)
                        if (item.File != null)
                        {
                            item.ImgLoad = GetMassBinary(item.File);
                            if (item.ImgLoad != null)
                            {
                                item.ImgLink = null;
                                item.File = null;
                            }
                            else
                            {
                                err = true;
                                goto link;
                            }
                        }

                _allNews.SaveNews(news);
                TempData["message"] = news.Title + " " + _localizer["SaveNews"];
                return RedirectToAction("Index");
            }

            ViewBag.Categories = _category;
            //Что-то не так со значениями данных
            return View(news);
        }

        public ActionResult Create()
        {
            ViewBag.Categories = _category;
            return View("Edit", new News());
        }


        [HttpPost]
        public IActionResult Delete(int newsId)
        {
            var deletedNews = _allNews.DeleteNews(newsId);
            if (deletedNews != null) TempData["message"] = deletedNews.Title + " " + _localizer["DeletedNews"];
            return RedirectToAction("Index");
        }
    }
}

HackedNews/Controllers/NewsController.cs
using System.Linq;
using HackedNews.Data.Interfaces;
using HackedNews.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace HackedNews.Controllers
{
    public class NewsController : Controller
    {
        private readonly IAllNews allNews;
        public int PageSize = 10; //для разбиения на страницы


        public NewsController(IAllNews _allNews)
        {
            allNews = _allNews;
        }


        public ActionResult List(int? categoryId, int NewsPage = 1)
        {
            return View(new NewsListViewModel
            {
                News = allNews.News.Where(p => categoryId == null || p.CategoryId == categoryId)
                    .OrderBy(p => p.Id)
                    .Skip((NewsPage - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = NewsPage,
                    ItemsPerPage = PageSize,
                    TotalItems = categoryId == null
                        ? allNews.News.Count()
                        : allNews.News.Count(news => news.CategoryId == categoryId)
                },
                CurrentCategory = categoryId
            });
        }

        public ActionResult InfNews(int? newsId)
        {
            var news = allNews.News.Where(news => news.Id == newsId);

            return View(
                new NewsListViewModel
                {
                    News = allNews.News.Where(news => news.Id == newsId)
                }
            );
        }
    }
}

HackedNews/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            background-color: #fee;
            border-color: red;
        }
    </style>
    <link href="~/css/site.css" rel="stylesheet"/>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body class="d-flex flex-column min-vh-100">
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" style="color: whitesmoke">HackedNews</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample07">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                            @Localizer["HomeBtn"] <span class="sr-only">(current)</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container wrapper flex-grow-1">
    <main role="main" class="pb-3" style="min-height: 100%">
        @*<div class="bg-info p-2 row">
            <div class="col">
                <h4>@ViewBag.Title</h4>
            </div>
            <div class="col-2">
                <a class="btn btn-sm btn-primary" asp-action="Logout" asp-controller="Account">Log Out</a>
            </div>
        </div>*@

        @*Располагаем здесь, чтобы не плодить подобные решение, если появятся новые представления для администрирования*@

        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        else if (TempData["err_message"] != null)
        {
            <div class="alert alert-warning">@TempData["err_message"]</div>
        }
        @RenderBody()
    </main>
</div>
<footer class="border-top pt-4 text-muted" style="line-height: 45px">
    <div class="container">
        <div class="row offset-md-2">
            <div class="col-4 col-md-5">
                <h5>@Localizer["ContactsText"]</h5>
                <ul class="list-unstyled text-small">
                    <li>Email: <a class="text-muted" href="mailto:artem_74@tut.by">artem_74@tut.by</a></li>
                    <li>Telegram: <a class="text-muted" href="https://t.me/TriangleMouse">Артем</a></li>
                </ul>
            </div>
            <div class="col-md-6">
                &copy; 2021 - HackedNews - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

HackedNews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>HackedNews</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body class="d-flex flex-column min-vh-100">
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HackedNews</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" title="Manage">@User.Identity.Name</a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline">
                                <button type="submit" class="nav-link btn btn-link text-dark" asp-action="Logout" asp-controller="Account">@Localizer["LogOutBtn"]</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">@Localizer["RegisterBtn"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">@Localizer["LogInBtn"]</a>
                        </li>
                    }
                </ul>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["HomeBtn"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="List">@Localizer["AllNewsBtn"]</a>
                    </li>
                    @if (User.Identity.Name == "ArtemAdmin_74@tut.by")
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">@Localizer["PageAdminBtn"]</a>
                        </li>
                    }
                </ul>

            </div>
            <div class="col-2">
                @await Html.PartialAsync("_SelectLanguagePartial")
            </div>
        </div>
    </nav>
</header>
<div class="container wrapper flex-grow-1">
    <main role="main" class="pb-3" style="min-height: 100%">
        @RenderBody()
    </main>
</div>
<footer class="border-top pt-4 text-muted" style="line-height: 45px">
    <div class="container">
        <div class="row offset-md-2">
            <div class="col-4 col-md-5">
                <h5>@Localizer["ContactsText"]</h5>
                <ul class="list-unstyled text-small">
                    <li>Email: <a class="text-muted" href="mailto:artem_74@tut.by">artem_74@tut.by</a></li>
                    <li>Telegram: <a class="text-muted" href="https://t.me/TriangleMouse">Артем</a></li>
                </ul>
            </div>
            <div class="col-md-6">
                &copy; 2021 - HackedNews - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", false)
</body>
</html>

HackedNews/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Localization
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}

<form asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" method="post" class="form-horizontal">
    <select name="culture" class="form-control" onchange="this.form.submit();" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
</form>